apiVersion: v1
kind: Pod
metadata:
  name: cowrie-pod
  labels:
    app: cowrie
spec:
  containers:
  - name: cowrie
    image: cowrie/cowrie:latest
    ports:
      - containerPort: 2222
      - containerPort: 2223
