apiVersion: v1
kind: Pod
metadata:
  name: cowrie-pod
  labels:
    app: cowrie
spec:
  containers:
  - name: cowrie
    image: cowrie/cowrie:latest
    securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
    capabilities:
        drop:
          - all
    ports:
      - name: ssh-port
        containerPort: 2222
        hostPort: 22
      - name: telnet-port
        containerPort: 2223
        hostPort: 23
    readinessProbe:
      tcpSocket:
        port: 2222
      initialDelaySeconds: 5
      periodSeconds: 60
    livenessProbe:
      tcpSocket:
        port: 2222
      initialDelaySeconds: 15
      periodSeconds: 60
