apiVersion: v1
kind: Pod
metadata:
  name: cowrie-pod
  labels:
    app: cowrie
spec:
  containers:
  - name: cowrie
    image: cowrie/cowrie:latest
    securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
    capabilities:
        drop:
          - all
    ports:
      - containerPort: 2222
      - containerPort: 2223
